# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained true
    - name: publish Windows
      run: dotnet publish -c Release -r win-x64 --self-contained true
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: |
          src/ServerFileDownloader/bin/Release/net8.0/linux-x64/publish/
          src/ServerFileDownloader/bin/Release/net8.0/win-x64/publish/
          
